#version: '3'
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8091"
#    restart: always
#    volumes:
#      - .:/app
version: "3"
services:
  web:
    build: .
    ports:
      - "7007:7007"
    volumes:
      - .:/app